Fix previous change of the Makefile and add workaround. Fix Makefile: With the last change the HAVE_LIBUSB code has been duplicated. Now the HAVE_LIBUSB code at the original place has been deleted.
Added a btstack_config.h for a workaround:
If MICROPY_BLUETOOTH_BTSTACK_USB is set and ENABLE_SCO_OVER_HCI is not defined
there is a compiler error:
    ../../lib/btstack/platform/libusb/hci_transport_h2_libusb.c:1354:13:
    error: ‘signal_sco_can_send_now’ defined but not used
Because the problem is in an external code a workaround is done by
defining MICROPY_BLUETOOTH_BTSTACK_USB in the added btstack_config.h